################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor=eDP-1,1920x1080@143.98,0x0,1.0
monitor=HDMI-A-1,1920x1080@99.93,auto-left,1


