# windowrule = minsize 600 500,class:*
# Example: Thunar always floats and is 950×600 px
# Make Dolphin float and set its size
windowrulev2 = float, class:^(org\.kde\.dolphin)$
windowrulev2 = size 900 700, class:^(org\.kde\.dolphin)$
